export { default as Header } from './header/Header'
export { default as Main } from './main/Main'
export { default as Footer } from './footer/Footer'
export { default as Card } from './card/Card'
export { default as ProtectedRoute } from './protectedRoute/ProtectedRoute'
export { default as BlackTooltip } from './BlackTooltip/BlackTooltip'
export { default as Preloader } from './preloader/Preloader'
export { default as SwiperArrows } from './swiperArrows/SwiperArrows'
